name: freq
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  HOST: ${{ secrets.HOST }}
  USER: ${{ secrets.USER }}
  PASSWD: ${{ secrets.PASSWD }}
  DB: ${{ secrets.DB }}
  CAPATH: ${{ secrets.CAPATH }}
jobs:
  freq: runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - run: pip install mysql
      - run: python freq.py
